name: default
contents: |
  rO0ABXcEAAAAKXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
  dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
  bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl
  Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA
  AAN0AAI9PXQAAXZ0AAR0eXBldXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1T
  dGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5n
  Lk51bWJlcoaslR0LlOCLAgAAeHAAAAoadAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAA
  AANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAAoadAAPRkxJTlRfQU5EX1NU
  RUVMc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4ACnVxAH4ABgAAAANxAH4ADHNx
  AH4ADQAAChp0AAtGSVNISU5HX1JPRHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4A
  CXEAfgAKdAAGYW1vdW50dXEAfgAGAAAABHEAfgAMc3EAfgANAAAKGnQAC0NPT0tFRF9CRUVGc3EA
  fgANAAAAA3NxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AIHVxAH4ABgAA
  AARxAH4ADHNxAH4ADQAAChp0AAtDT0JCTEVTVE9ORXNxAH4ADQAAAEBwcHBwcHBwcHBwcHBwcHBw
  cHBwcHBwcHBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAA
  A3EAfgAMc3EAfgANAAAKGnQACklST05fQk9PVFNzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhx
  AH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAMc3EAfgANAAAKGnQADUlST05fTEVHR0lOR1NzcQB+AABz
  cQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXEAfgAKdXEAfgAGAAAAA3EAfgAMc3EAfgANAAAKGnQA
  D0lST05fQ0hFU1RQTEFURXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+
  AAYAAAADcQB+AAxzcQB+AA0AAAoadAALSVJPTl9IRUxNRVRw
armor: |
  rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
  dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
  bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl
  Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA
  AAN0AAI9PXQAAXZ0AAR0eXBldXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1T
  dGFja3NyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5n
  Lk51bWJlcoaslR0LlOCLAgAAeHAAAAoadAAKSVJPTl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAA
  AANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+AA0AAAoadAANSVJPTl9MRUdHSU5H
  U3NxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+AAp1cQB+AAYAAAADcQB+AAxzcQB+
  AA0AAAoadAAPSVJPTl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlx
  AH4ACnVxAH4ABgAAAANxAH4ADHNxAH4ADQAAChp0AAtJUk9OX0hFTE1FVA==
